name: "Adrian's Test Website"
favicon: null
layout_spectrum: 0.84953
typography_spectrum: 0.44891667482443154
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0f0f0d'
    - '#a5c0ed'
    - '#d72f2f'
    - '#4a4c25'
  brandStrength: 0.6875
  lightness: 0.320311741437763
  saturation: 0.8203031297307462
  rhythmicContrast: 0.3807868058793247
purpose: []
